repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: [--fix]
        exclude: |
          migrations/
          | __pycache__/
          | .pytest_cache/
          | .git/
          | .venv/
          | env/
          | build/
          | dist/
          | static/
          | media/
          | ^.*\.(md|json|yml|yaml|toml|lock|ini|env)$
          
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        exclude: |
          migrations/
          | __pycache__/
          | .pytest_cache/
          | .git/
          | .venv/
          | env/
          | build/
          | dist/
          | static/
          | media/
          | ^.*\.(md|json|yml|yaml|toml|lock|ini|env)$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: []
        exclude: |
          migrations/
          | __pycache__/
          | .pytest_cache/
          | .git/
          | .venv/
          | env/
          | build/
          | dist/
          | static/
          | media/
          | ^.*\.(md|json|yml|yaml|toml|lock|ini|env)$
