name: DRF CI/CD

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  IMAGE_NAME: nyobeelouga5/drf-api
  PYTHON_VERSION: '3.10'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install lint tools (ruff, black, flake8)
        run: |
          pip install --upgrade pip
          pip install ruff black flake8
      - name: Ruff check
        run: ruff check . --fix
      - name: Black format
        run: black .
      - name: Flake8 lint
        run: flake8 .

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Bandit
        run: pip install bandit
      - name: Bandit security scan
        run: bandit -r . -c .bandit

  test:
    needs: [lint, security]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      DJANGO_SETTINGS_MODULE: core.settings
      SECRET_KEY: testsecretkey
      DEBUG: 1
      GITHUB_CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
      GITHUB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
      - name: Wait for Postgres to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 1; done
      - name: Run Django tests
        run: |
          set -e
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh

  build_and_push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and tag Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN
          railway up --service ParkApp